// Australian-focused pet food brand catalog
// Organized by category for dropdown selection

export const KIBBLE_BRANDS = [
    'Royal Canin',
    'Hills Science Diet',
    'Advance',
    'Black Hawk',
    'Ivory Coat',
    'Ziwi Peak',
    'Open Farm',
    'Meals for Mutts',
    'Prime100',
    'Savour Life',
    'Supercoat',
    'My Dog',
    'Pedigree',
    'Optimum',
    'Eukanuba',
    'Pro Plan (Purina)',
    'Acana',
    'Orijen',
    'Canidae',
    'Nutro',
    'Taste of the Wild',
    'Wellness',
    'Blue Buffalo',
    'Instinct',
    'Merrick',
    'Vetalogica',
    'Leaps & Bounds',
    'Nature\'s Gift',
];

export const TREAT_BRANDS = [
    'Greenies',
    'Schmackos',
    'WAG',
    'Barkly',
    'Ziwi Peak',
    'Prime100',
    'Whimzees',
    'K9 Natural',
    'Vetalogica',
    'Savour Life',
    'Love\'em',
    'Bow Wow',
    'Rufus & Coco',
    'Good Noze',
    'Dogsee',
    'Pedigree Dentastix',
    'Leaps & Bounds',
];

export const WET_FOOD_BRANDS = [
    'Royal Canin',
    'Hills Science Diet',
    'Ziwi Peak',
    'Fancy Feast',
    'Optimum',
    'My Dog',
    'Pedigree',
    'Black Hawk',
    'K9 Natural',
    'Feline Natural',
    'Applaws',
    'Wellness',
    'Instinct',
    'Blue Buffalo',
    'Ivory Coat',
    'Nature\'s Gift',
    'Dine',
    'Whiskas',
];

export const BOWL_SIZES: { label: string; value: 'small' | 'medium' | 'large' | 'xl'; description: string }[] = [
    { label: 'Small', value: 'small', description: '~1 cup / 250ml' },
    { label: 'Medium', value: 'medium', description: '~2 cups / 500ml' },
    { label: 'Large', value: 'large', description: '~3 cups / 750ml' },
    { label: 'XL', value: 'xl', description: '~4+ cups / 1L+' },
];
